### ISSUE TITLE
Api down

### ISSUE THREAD

**Issue by Gokusann1112** [KarlHlmgrn/crypto-oled#7]
Hello, I love the concept of having crypto prices on my keyboard, but sadly, I didn't manage to do this. When I tried to install the program (after following all the steps in the readme file), I encountered an error that said:

Traceback (most recent call last):
  File "C:\Users\pepik\Desktop\crypto-oled-2.0\crypto-oled-2.0\crypto-graphing.py", line 239, in <module>
    graph = getGraph(0)
            ^^^^^^^^^^^
  File "C:\Users\pepik\Desktop\crypto-oled-2.0\crypto-oled-2.0\crypto-graphing.py", line 96, in getGraph
    for i in data["prices"]:
             ~~~~^^^^^^^^^^
KeyError: 'prices'


I think there might be an API issue.

**Comment by KarlHlmgrn** [comment]
Yeah, coingecko seemingly have changed the API and I have to make some changes to make it work with the new API. I will try to make this work as fast as possible.

**Comment by pascal-00** [comment]
Has coingecko api become paid?

**Comment by KarlHlmgrn** [comment]
There is a known problem with the parsing of data from coingecko when an API change was implemented that has broken this application. If you have the knowledge and time you could create a pull request or wait for me to implement a fix. I will try to do this the coming month but we'll see.

**Comment by pascal-00** [comment]
How about using another api like the one used by the apex-tux linux app that uses coindesk ?
https://api.coindesk.com/v1/bpi/currentprice.json
Except that I think it only tells you the price of bitcoin, not other currencies and the app is not designed to show only bitcoin

**Comment by KarlHlmgrn** [comment]
I believe when I started this project coindesk didn't allow free access to historic data which coingecko provided at the time (and I believe now as well). This application doesn't just provide the current value it also shows a graph that can be scrolled through which requires the historic data.
